Add setting jupyter.newCellOnRunLast (#7995)
* add setting jupyter.newCellOnRunLast

* fix CI error TS2420: Property 'newCellOnRunLast' is missing in type 'JupyterSettings' but required in type 'IWatchableJupyterSettings'