[Functional test fix] ExtensionSurveyBanner.bannerMessage s/Python/Jupyter/
As I’m figuring out hot this repository work, I ran the functional tests locally and found out that some of them are broken. Is it acknowledge that they’re broken or are they broken just for me?

The failed functional tests are as follows:

1. `Daemon Execute a file and handle error: AssertionError: expected promise to be rejected with an error including 'KABOOM' but it was fulfilled with null`
2. `Daemon - Python Daemon Pool Execute a file and handle error: AssertionError: expected promise to be rejected with an error including 'KABOOM' but it was fulfilled with null`
3. `AssertionError [ERR_ASSERTION]: LanguageService string doesnt match` (the one I’m addressing in this PR).
4. `Localization keys exist: AssertionError [ERR_ASSERTION]: Missing keys. Add the following to package.nls.json: "InsidersNativeNotebooksSurveyBanner.bannerMessage" : "Can you please take a minute to tell us about your notebooks experience in VS Code?", "DataScience.pythonInstalledReloadPromptMessage" : "Python extension is now installed. Some features might not be available until a notebook or interactive window session is restarted.", "DataScience.activatingEnvironment" : "Activating Python Environment '{0}'",`
5. `"after all" hook: afterAll in "{root}": Error: Cannot find module '../platform/datascience/kernel-launcher/kernelLauncher'`.

Besides the issue I’m addressing here,

The other localization test seems to be fixed by:

```diff
--- a/package.nls.json
+++ b/package.nls.json
@@ -571,5 +571,8 @@
     "Installer.searchForHelp": "Search for help",
     "Installer.couldNotInstallLibrary": "Could not install {0}. If pip is not available, please use the package manager of your choice to manually install this library into your Python environment.",
     "Installer.dataScienceInstallPrompt": "Data Science library {0} is not installed. Install?",
-    "Products.installingModule": "Installing {0}"
+    "Products.installingModule": "Installing {0}",
+    "InsidersNativeNotebooksSurveyBanner.bannerMessage" : "Can you please take a minute to tell us about your notebooks experience in VS Code?",
+    "DataScience.pythonInstalledReloadPromptMessage" : "Python extension is now installed. Some features might not be available until a notebook or interactive window session is restarted.",
+    "DataScience.activatingEnvironment" : "Activating Python Environment '{0}'"
 }
```

The error in the Python daemon is weird because the exception rises correctly in the `baseDaemon`'s exec function, but then it goes to the pythonExecutionService, going through this if:

```diff
  if (ex instanceof DaemonError || ex instanceof ConnectionClosedError) {
    traceWarning('Falling back to Python Execution Service due to failure in daemon', ex);
    return this.pythonExecutionService.exec(args, options)
```

And that daemon just returns null.

---

Feedback always appreciated!